import { describe, it, expect } from "vitest";
import { writeFile, rm, mkdir, symlink } from "node:fs/promises";
import { join } from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { makeScratchRepo } from "./helpers/scratch-repo.js";
import { createWorktree, changedFiles, fileAtCommit } from "../src/daemon/worktree.js";

const exec = promisify(execFile);
const ID = "67d92140-3dd1-4311-aed8-c079ba03eba6";

/** The worktree, ready to be written into. */
async function specialist() {
  const repo = await makeScratchRepo();
  const { worktree, branch } = await createWorktree(repo, "auth", ID);
  const git = (...args: string[]) => exec("git", args, { cwd: worktree });
  await git("config", "user.email", "spec@example.com");
  await git("config", "user.name", "Spec");
  return { repo, worktree, branch, git };
}

const pathsOf = (files: { path: string }[]) => files.map((f) => f.path).sort();

/**
 * What a specialist has actually done to a repo, which is the question the
 * editor's sidebar asks. `inspectWorktree` already parses this and returns
 * only a count - see #128.
 */
describe("changedFiles", () => {
  it("reports nothing for a worktree nobody has touched", async () => {
    const { repo, worktree, branch } = await specialist();
    const { files } = await changedFiles(repo, worktree, branch);
    expect(files).toEqual([]);
  });

  it("reports a file the specialist has not committed yet", async () => {
    const { repo, worktree, branch } = await specialist();
    await writeFile(join(worktree, "README.md"), "changed\n");

    const { files } = await changedFiles(repo, worktree, branch);
    expect(files).toEqual([
      { path: "README.md", status: "M", committed: false },
    ]);
  });

  it("reports a new file the specialist has not committed yet", async () => {
    const { repo, worktree, branch } = await specialist();
    await writeFile(join(worktree, "new.ts"), "export const a = 1;\n");

    const { files } = await changedFiles(repo, worktree, branch);
    expect(files).toEqual([{ path: "new.ts", status: "A", committed: false }]);
  });

  /**
   * The reason the base is the branch's starting point rather than its HEAD.
   * Specialists commit as they work, and a tree that empties itself on every
   * commit goes blank exactly when there is most to look at.
   */
  it("still reports work after the specialist has committed it", async () => {
    const { repo, worktree, branch, git } = await specialist();
    await writeFile(join(worktree, "README.md"), "changed\n");
    await git("add", "-A");
    await git("commit", "-q", "-m", "work");

    const { files } = await changedFiles(repo, worktree, branch);
    expect(files).toEqual([{ path: "README.md", status: "M", committed: true }]);
  });

  it("reports committed and uncommitted work together", async () => {
    const { repo, worktree, branch, git } = await specialist();
    await writeFile(join(worktree, "one.ts"), "1\n");
    await git("add", "-A");
    await git("commit", "-q", "-m", "one");
    await writeFile(join(worktree, "two.ts"), "2\n");

    const { files } = await changedFiles(repo, worktree, branch);
    expect(pathsOf(files)).toEqual(["one.ts", "two.ts"]);
    expect(files.find((f) => f.path === "one.ts")!.committed).toBe(true);
    expect(files.find((f) => f.path === "two.ts")!.committed).toBe(false);
  });

  /**
   * A file edited, committed, and then edited again is one file with more
   * work in it - not two rows saying different things about the same path.
   */
  it("names a file once when it has been both committed and edited since", async () => {
    const { repo, worktree, branch, git } = await specialist();
    await writeFile(join(worktree, "README.md"), "once\n");
    await git("add", "-A");
    await git("commit", "-q", "-m", "once");
    await writeFile(join(worktree, "README.md"), "twice\n");

    const { files } = await changedFiles(repo, worktree, branch);
    expect(files).toHaveLength(1);
    // Uncommitted wins: it is the state on disk, and it is the one the
    // developer can still do something about.
    expect(files[0]).toEqual({ path: "README.md", status: "M", committed: false });
  });

  it("reports a deletion", async () => {
    const { repo, worktree, branch } = await specialist();
    await rm(join(worktree, "README.md"));

    const { files } = await changedFiles(repo, worktree, branch);
    expect(files).toEqual([{ path: "README.md", status: "D", committed: false }]);
  });

  /**
   * `node_modules` is a symlink into the developer's own checkout and the
   * lockfile gets regenerated by anything that runs a package manager. Left
   * in, every worktree looks entirely rewritten. `inspectWorktree` already
   * refuses to count these; this must refuse to name them.
   */
  it("never names Bench's own leavings", async () => {
    const { repo, worktree, branch } = await specialist();
    await symlink(join(repo, "node_modules"), join(worktree, "node_modules")).catch(() => {});
    await writeFile(join(worktree, "pnpm-lock.yaml"), "lockfile: {}\n");
    await mkdir(join(worktree, ".bench", "reports"), { recursive: true });
    await writeFile(join(worktree, ".bench", "reports", "x.html"), "<p>x</p>");
    await writeFile(join(worktree, "real.ts"), "export const a = 1;\n");

    const { files } = await changedFiles(repo, worktree, branch);
    expect(pathsOf(files)).toEqual(["real.ts"]);
  });

  it("says which commit it measured from, so a caller can read the other side", async () => {
    const { repo, worktree, branch } = await specialist();
    const { base } = await changedFiles(repo, worktree, branch);

    const { stdout } = await exec("git", ["rev-parse", "HEAD"], { cwd: repo });
    expect(base).toBe(stdout.trim());
  });

  it("gives back nothing rather than throwing when the worktree is gone", async () => {
    const { repo, branch } = await specialist();
    const { files, base } = await changedFiles(repo, "/nonexistent/worktree", branch);
    expect(files).toEqual([]);
    expect(base).toBeNull();
  });
});

/**
 * The left-hand side of a diff. The right-hand side is the file on disk,
 * which the editor can open by itself; this is the half only git has.
 */
describe("fileAtCommit", () => {
  it("gives back the file as it was", async () => {
    const { worktree, repo, branch } = await specialist();
    await writeFile(join(worktree, "README.md"), "changed\n");
    const { base } = await changedFiles(repo, worktree, branch);

    expect(await fileAtCommit(worktree, base!, "README.md")).toBe("scratch\n");
  });

  /** A file the specialist created did not exist at the base. An empty left
   * side is what makes the diff read as "all of this is new". */
  it("gives back empty for a file that did not exist yet", async () => {
    const { worktree, repo, branch } = await specialist();
    const { base } = await changedFiles(repo, worktree, branch);

    expect(await fileAtCommit(worktree, base!, "brand-new.ts")).toBe("");
  });

  /**
   * The path arrives on a URL query string. git refuses to resolve outside
   * the repository itself, but a route that hands user input to a shell
   * should not be relying on that alone.
   */
  it("refuses to climb out of the worktree", async () => {
    const { worktree, repo, branch } = await specialist();
    const { base } = await changedFiles(repo, worktree, branch);

    expect(await fileAtCommit(worktree, base!, "../../../etc/passwd")).toBeNull();
    expect(await fileAtCommit(worktree, base!, "/etc/passwd")).toBeNull();
  });

  it("gives back null rather than throwing on a commit that does not exist", async () => {
    const { worktree } = await specialist();
    expect(await fileAtCommit(worktree, "0".repeat(40), "README.md")).toBeNull();
  });
});
