/**
 * The home-screen icons, rendered from src/client/icon.svg.
 *
 * A manifest may point at an SVG and Chrome will take it, but iOS will not:
 * an installed Bench on an iPhone uses the apple-touch-icon and nothing else,
 * and that has to be a PNG. So the one drawing is rasterised here, checked in
 * beside it, and regenerated by hand when the mark changes - which is far
 * rarer than a build, and not worth making every build carry ImageMagick.
 *
 * Usage: node scripts/icons.mjs
 */
import { spawn } from "node:child_process";
import { mkdir } from "node:fs/promises";
import { join } from "node:path";

const SOURCE = "src/client/icon.svg";
const OUT = "src/client/icons";

/** 192 and 512 are what a manifest is asked for; 180 is what iOS takes. */
const SIZES = [
  { size: 512, file: "icon-512.png" },
  { size: 192, file: "icon-192.png" },
  { size: 180, file: "apple-touch-icon.png" },
];

/** 512 * (192/96): rasterise once well above the largest icon, then come
 * down to each size, so nothing is scaled up from a coarse render. */
const DENSITY = 192;

const convert = (args) =>
  new Promise((resolve, reject) => {
    const child = spawn("convert", args, { stdio: ["ignore", "ignore", "inherit"] });
    child.on("error", () => reject(new Error(
      "bench: needs ImageMagick (`convert`) to redraw the icons. The PNGs in"
      + " src/client/icons are checked in, so this is only needed when the mark changes.",
    )));
    child.on("exit", (code) => (code === 0 ? resolve() : reject(new Error(`convert exited ${code}`))));
  });

await mkdir(OUT, { recursive: true });

for (const { size, file } of SIZES) {
  const out = join(OUT, file);
  await convert([
    "-background", "none", "-density", String(DENSITY), SOURCE,
    "-resize", `${size}x${size}`,
    // The icon carries its own ground, so there is nothing for transparency
    // to do except make a launcher guess at what is behind it.
    "-alpha", "remove", "-alpha", "off",
    "-depth", "8", "-strip",
    out,
  ]);
  process.stdout.write(`bench: ${out} (${size}px)\n`);
}
